import mongoose from "mongoose";

const ProductSchema = new mongoose.Schema({
    title: { type: String, required: true, default: "Untitled Product" },
    seller_name: { type: String, default: "Unknown Seller" },
    brand: { type: String, default: "No Brand" },
    description: { type: String, default: "No description available." },
    initial_price: { type: Number, default: 0 },
    final_price: { type: Number, default: 0 },
    currency: { type: String, default: "USD" },
    availability: { type: String, default: "In Stock" },
    reviews_count: { type: Number, default: 0 },
    categories: { type: [String], default: [] },
    buybox_seller: { type: String, default: "Unknown" },
    number_of_sellers: { type: Number, default: 1 },
    root_bs_rank: { type: Number, default: 0 },
    answered_questions: { type: Number, default: 0 },
    domain: { type: String, default: "amazon.com" },
    images_count: { type: Number, default: 0 },
    url: { type: [String], default: "#" },
    video_count: { type: Number, default: 0 },
    image_url: { type: [String], default: [] },
    item_weight: { type: String, default: "Unknown" },
    rating: { type: Number, default: 0 },
    product_dimensions: { type: String, default: "Not specified" },
    seller_id: { type: String, default: "Unknown" },
    date_first_available: { type: Date, default: Date.now },
    discount: { type: String, default: "0%" },
    model_number: { type: String, default: "N/A" },
    manufacturer: { type: String, default: "Unknown" },
    department: { type: String, default: "General" },
    plus_content: { type: Boolean, default: false },
    upc: { type: String, default: "N/A" },
    video: { type: Boolean, default: false },
    top_review: { type: String, default: "No reviews yet." },
    variations: { type: [Object], default: [] },
    delivery: { type: [String], default: [] },
    features: { type: [String], default: [] },
    format: { type: String, default: "Standard" },
    buybox_prices: { type: [Object], default: [] },
    parent_asin: { type: String, default: "N/A" },
    input_asin: { type: String, default: "N/A" },
    ingredients: { type: String, default: "Not specified" },
    origin_url: { type: String, default: "#" },
    bought_past_month: { type: Number, default: 0 },
    is_available: { type: Boolean, default: true },
    root_bs_category: { type: String, default: "Unknown" },
    bs_category: { type: String, default: "Unknown" },
    bs_rank: { type: Number, default: 0 },
    badge: { type: String, default: "None" },
    subcategory_rank: { type: Number, default: 0 },
    amazon_choice: { type: Boolean, default: false },
    images: { type: [String], default: [] },
    product_details: { type: Object, default: {} },
    prices_breakdown: { type: Object, default: {} },
    country_of_origin: { type: String, default: "Unknown" },
},{ timestamps: true });

export default mongoose.models.Product || mongoose.model("Product", ProductSchema);
